export const metadata = {
  title: "Terms of Service | Notch Tools",
  description: "Read the terms of service for using Notch Tools.",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-12 lg:px-8">
      <div className="space-y-8">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
            Terms of Service
          </h1>
          <p className="mt-4 text-sm text-muted-foreground">
            Last updated: October 24, 2023
          </p>
        </div>

        <div className="prose prose-gray dark:prose-invert max-w-none space-y-6">
          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-foreground">1. Acceptance of Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              By accessing and using Notch Tools (the "Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by these terms, please do not use this Service.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-foreground">2. Description of Service</h2>
            <p className="text-muted-foreground leading-relaxed">
              Notch Tools provides an array of free web-based utilities and developer tools. We reserve the right to modify, suspend, or discontinue the Service with or without notice at any time and without any liability to you.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-foreground">3. Use of Tools</h2>
            <p className="text-muted-foreground leading-relaxed">
              Our tools are provided "as is". While we strive for accuracy, we make no guarantees regarding the exactness, reliability, or completeness of the output generated by our tools. You are solely responsible for verifying the output before using it in a production environment or relying on it for critical tasks.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-foreground">4. User Data & Processing</h2>
            <p className="text-muted-foreground leading-relaxed">
              As outlined in our Privacy Policy, the majority of processing occurs client-side in your web browser. You retain all ownership rights to the data you process using our tools. We do not claim any ownership over your inputs or outputs.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-foreground">5. Limitation of Liability</h2>
            <p className="text-muted-foreground leading-relaxed">
              In no event shall Notch Tools or its creators be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
